# @package uncertainty_aggregation

# Configuration for Uncertainty Aggregation Methods

# Enable/disable different methods
enabled_methods:
  calibration_based: true
  rank_based: true
  temperature_scaling: true
  meta_learning: true
  bayesian_averaging: true

# Method-specific configurations
calibration_based:
  calibration_method: "isotonic"  # isotonic, platt
  out_of_bounds: "clip"
  validation_split: 0.2

rank_based:
  normalization_method: "percentile"  # percentile, z_score
  aggregation_method: "mean"  # mean, median, weighted_mean

temperature_scaling:
  optimizer: "LBFGS"
  max_iter: 50
  lr: 0.01

meta_learning:
  model_type: "random_forest"  # random_forest, xgboost, neural_network
  n_estimators: 100
  random_state: 42
  validation_split: 0.2
  features:
    - individual_uncertainties
    - model_confidences
    - consensus_metrics

bayesian_averaging:
  prior_type: "uniform"  # uniform, informative
  likelihood_method: "confidence_based"
  posterior_method: "exact"  # exact, variational

# Evaluation metrics
evaluation:
  metrics:
    - predictive_accuracy
    - calibration_error
    - sharpness
    - ensemble_diversity
  calibration:
    n_bins: 10
    strategy: "uniform"  # uniform, quantile

# Quality thresholds
quality_thresholds:
  min_predictive_accuracy: 0.6
  max_calibration_error: 0.1
  min_sharpness: 0.1
  min_diversity: 0.1
